### ISSUE TITLE
UnauthorizedError: No authorization token was found

### ISSUE THREAD

**Issue by pyraman** [PacktPublishing/Handson-Blockchain-Development-with-Hyperledger#2]
I've try to deploy the network on 6 physical Red Hat machines. Everything seems fine. I was able to deploy/invoking trade_workflow chaincode.
I was able to start the server also - node app.js.
but when navigating to http://localhost.com:4000. I got exception:

UnauthorizedError: No authorization token was found
    at middleware (/root/Trade-Network/application/node_modules/express-jwt/lib/index.js:76:21)
    at /root/Trade-Network/application/node_modules/express-unless/index.js:47:5
    at Layer.handle [as handle_request] (/root/Trade-Network/application/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/Trade-Network/application/node_modules/express/lib/router/index.js:317:13)
    at /root/Trade-Network/application/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/Trade-Network/application/node_modules/express/lib/router/index.js:335:12)
    at next (/root/Trade-Network/application/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/root/Trade-Network/application/node_modules/body-parser/lib/types/urlencoded.js:91:7)
    at Layer.handle [as handle_request] (/root/Trade-Network/application/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/Trade-Network/application/node_modules/express/lib/router/index.js:317:13)

**Comment by pyraman** [comment]
I executed this command:
curl -s -X POST http://localhost:4000/login -H "content-type: application/x-wwwform-urlencoded" -d 'username=Jim&orgName=importerorg'

result: 
[2018-09-27 14:08:13.991] [DEBUG] TradeApp -  ------>>>>>> new request for /login
[2018-09-27 14:08:13.991] [DEBUG] TradeApp - User name for login/registration : undefined
[2018-09-27 14:08:13.991] [DEBUG] TradeApp - Org name  : undefined

**Comment by pyraman** [comment]
It's my bad - not read document carefully.
